### ISSUE TITLE
vcn submit attachments

### ISSUE THREAD

**Issue by dmacvicar** [codenotary/vcn#133]
# Story

The use case is to give context to a notarization, just like attributes do. For example, attaching a security scan report when notarizing a docker image, and examining it later when the notarization is reviewed.

# Proposal

As discussed with @mmeloni a possible UX would be:

```
vcn n --attach secreport.html --attach output.pdf --attr env=production docker://foobar 
```

This would create a manifest:

```
Kind: docker
Name: foobar
Hash: 9435347598347589734985798754393458
Metadata:
  docker: ....
  env=production
Attachments:
  - Filename: secreport.html
    Hash: 675478654786547856786478647864567884674
  - Filename: output.pdf
    Hash: 423409865095489045868049569045806809458
```

And during notarization, the following would be inserted atomically in the ledger:

```
vcn.$AssetHash.Attachment.$AttachmentHash -> content
```

## Alternatives

* We thought about using the same attributes concepts for attachments, but that would require having a convention for when the attribute value is not in the manifest but attached/referenced, which needs to be distinguishable from a real attribute value.

## Other things to consider

* The filename attribute is only meant for the UI to be able to give some semantics to the attachment. The attachment is stored by asset hash and content hash. We may need to consider adding a mime-type attribute to the attachment entry in the manifest as well.

* The current upload implementation (which is being revisited in this card) does not use streams yet.
  The notarize command should check that all attachments do not exceed certain size, at least until we change the implementation to use streams.

**What would you like to be added or enhanced**

**Why is this needed**

**Additional context**
